--------------------------------------------------------
--  File created - Wednesday-August-15-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTENDING
--------------------------------------------------------

  CREATE TABLE "C##ADAMJDBC"."ATTENDING" 
   (	"ATTENDING_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"COURSE_ID" NUMBER(*,0), 
	"STUDENT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "C##ADAMJDBC"."COURSE" 
   (	"COURSE_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"COURSE_NAME" VARCHAR2(255 BYTE), 
	"MINIMUN_GPA" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INSTRUCTOR
--------------------------------------------------------

  CREATE TABLE "C##ADAMJDBC"."INSTRUCTOR" 
   (	"INSTRUCTOR_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FULL_NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"SPECIALITY" VARCHAR2(255 BYTE), 
	"ADMIN_ROLE" NUMBER(*,0), 
	"PASS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE "C##ADAMJDBC"."ITEM" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"QUANTITY_IN_STOCK" NUMBER(*,0), 
	"PRICE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "C##ADAMJDBC"."STUDENT" 
   (	"STUDENT_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FULL_NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"GPA" NUMBER(5,2), 
	"PASS" VARCHAR2(255 BYTE), 
	"STUDENT_ROLE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEACHING
--------------------------------------------------------

  CREATE TABLE "C##ADAMJDBC"."TEACHING" 
   (	"TEACHING_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"COURSE_ID" NUMBER(*,0), 
	"INSTRUCTOR_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ADAMJDBC.ATTENDING
SET DEFINE OFF;
Insert into C##ADAMJDBC.ATTENDING (ATTENDING_ID,COURSE_ID,STUDENT_ID) values (1,1,3);
Insert into C##ADAMJDBC.ATTENDING (ATTENDING_ID,COURSE_ID,STUDENT_ID) values (2,2,3);
Insert into C##ADAMJDBC.ATTENDING (ATTENDING_ID,COURSE_ID,STUDENT_ID) values (22,4,1);
REM INSERTING into C##ADAMJDBC.COURSE
SET DEFINE OFF;
Insert into C##ADAMJDBC.COURSE (COURSE_ID,COURSE_NAME,MINIMUN_GPA) values (1,'Math',3.1);
Insert into C##ADAMJDBC.COURSE (COURSE_ID,COURSE_NAME,MINIMUN_GPA) values (2,'Science',3.2);
Insert into C##ADAMJDBC.COURSE (COURSE_ID,COURSE_NAME,MINIMUN_GPA) values (3,'English',3.1);
Insert into C##ADAMJDBC.COURSE (COURSE_ID,COURSE_NAME,MINIMUN_GPA) values (4,'GYM',2.8);
REM INSERTING into C##ADAMJDBC.INSTRUCTOR
SET DEFINE OFF;
Insert into C##ADAMJDBC.INSTRUCTOR (INSTRUCTOR_ID,FULL_NAME,EMAIL,SPECIALITY,ADMIN_ROLE,PASS) values (1,'Luke','luke@gmail.com','Mathemathician',0,'444');
Insert into C##ADAMJDBC.INSTRUCTOR (INSTRUCTOR_ID,FULL_NAME,EMAIL,SPECIALITY,ADMIN_ROLE,PASS) values (2,'lance','lance@gmail.com','scientis',0,'555');
Insert into C##ADAMJDBC.INSTRUCTOR (INSTRUCTOR_ID,FULL_NAME,EMAIL,SPECIALITY,ADMIN_ROLE,PASS) values (3,'mark','mark@gmail.com','important',1,'666');
REM INSERTING into C##ADAMJDBC.ITEM
SET DEFINE OFF;
Insert into C##ADAMJDBC.ITEM (ID,NAME,QUANTITY_IN_STOCK,PRICE) values (1,'Pen',5500,1);
Insert into C##ADAMJDBC.ITEM (ID,NAME,QUANTITY_IN_STOCK,PRICE) values (2,'Pencil',0,0.5);
Insert into C##ADAMJDBC.ITEM (ID,NAME,QUANTITY_IN_STOCK,PRICE) values (3,'Paper',0,8);
Insert into C##ADAMJDBC.ITEM (ID,NAME,QUANTITY_IN_STOCK,PRICE) values (4,'Post its',0,2);
Insert into C##ADAMJDBC.ITEM (ID,NAME,QUANTITY_IN_STOCK,PRICE) values (5,'Permanent Marker',0,5.5);
Insert into C##ADAMJDBC.ITEM (ID,NAME,QUANTITY_IN_STOCK,PRICE) values (6,'Pencil Sharpeners',0,3);
Insert into C##ADAMJDBC.ITEM (ID,NAME,QUANTITY_IN_STOCK,PRICE) values (7,'Pencil Case',0,2.5);
REM INSERTING into C##ADAMJDBC.STUDENT
SET DEFINE OFF;
Insert into C##ADAMJDBC.STUDENT (STUDENT_ID,FULL_NAME,EMAIL,GPA,PASS,STUDENT_ROLE) values (1,'Bairon Vasquez','b@gmail.com',3.4,'111',-1);
Insert into C##ADAMJDBC.STUDENT (STUDENT_ID,FULL_NAME,EMAIL,GPA,PASS,STUDENT_ROLE) values (2,'Yamil Burgos','y@gmail.com',3.4,'222',-1);
Insert into C##ADAMJDBC.STUDENT (STUDENT_ID,FULL_NAME,EMAIL,GPA,PASS,STUDENT_ROLE) values (3,'Joseph Robinson','J@gmail.com',3.9,'333',-1);
REM INSERTING into C##ADAMJDBC.TEACHING
SET DEFINE OFF;
Insert into C##ADAMJDBC.TEACHING (TEACHING_ID,COURSE_ID,INSTRUCTOR_ID) values (4,4,1);
Insert into C##ADAMJDBC.TEACHING (TEACHING_ID,COURSE_ID,INSTRUCTOR_ID) values (1,1,1);
Insert into C##ADAMJDBC.TEACHING (TEACHING_ID,COURSE_ID,INSTRUCTOR_ID) values (2,2,3);
Insert into C##ADAMJDBC.TEACHING (TEACHING_ID,COURSE_ID,INSTRUCTOR_ID) values (3,3,2);
--------------------------------------------------------
--  DDL for Index ATTENDING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADAMJDBC"."ATTENDING_PK" ON "C##ADAMJDBC"."ATTENDING" ("ATTENDING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADAMJDBC"."COURSE_PK" ON "C##ADAMJDBC"."COURSE" ("COURSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INSTRUCTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADAMJDBC"."INSTRUCTOR_PK" ON "C##ADAMJDBC"."INSTRUCTOR" ("INSTRUCTOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADAMJDBC"."STUDENT_PK" ON "C##ADAMJDBC"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEACHING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADAMJDBC"."TEACHING_PK" ON "C##ADAMJDBC"."TEACHING" ("TEACHING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "C##ADAMJDBC"."INSTRUCTOR" MODIFY ("INSTRUCTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."INSTRUCTOR" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."INSTRUCTOR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."INSTRUCTOR" MODIFY ("SPECIALITY" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."INSTRUCTOR" MODIFY ("ADMIN_ROLE" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."INSTRUCTOR" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."INSTRUCTOR" ADD CONSTRAINT "INSTRUCTOR_PK" PRIMARY KEY ("INSTRUCTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ADAMJDBC"."INSTRUCTOR" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "C##ADAMJDBC"."STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."STUDENT" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."STUDENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."STUDENT" MODIFY ("GPA" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."STUDENT" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."STUDENT" MODIFY ("STUDENT_ROLE" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ADAMJDBC"."STUDENT" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "C##ADAMJDBC"."COURSE" MODIFY ("COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."COURSE" MODIFY ("COURSE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."COURSE" MODIFY ("MINIMUN_GPA" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("COURSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ADAMJDBC"."COURSE" ADD UNIQUE ("COURSE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ATTENDING
--------------------------------------------------------

  ALTER TABLE "C##ADAMJDBC"."ATTENDING" MODIFY ("ATTENDING_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."ATTENDING" MODIFY ("COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."ATTENDING" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."ATTENDING" ADD CONSTRAINT "ATTENDING_PK" PRIMARY KEY ("ATTENDING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEACHING
--------------------------------------------------------

  ALTER TABLE "C##ADAMJDBC"."TEACHING" MODIFY ("TEACHING_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."TEACHING" MODIFY ("COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."TEACHING" MODIFY ("INSTRUCTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADAMJDBC"."TEACHING" ADD CONSTRAINT "TEACHING_PK" PRIMARY KEY ("TEACHING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTENDING
--------------------------------------------------------

  ALTER TABLE "C##ADAMJDBC"."ATTENDING" ADD CONSTRAINT "COURSE_ATT_FK" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "C##ADAMJDBC"."COURSE" ("COURSE_ID") ENABLE;
  ALTER TABLE "C##ADAMJDBC"."ATTENDING" ADD CONSTRAINT "STUDENT_ATT_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "C##ADAMJDBC"."STUDENT" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEACHING
--------------------------------------------------------

  ALTER TABLE "C##ADAMJDBC"."TEACHING" ADD CONSTRAINT "COURSE_FK" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "C##ADAMJDBC"."COURSE" ("COURSE_ID") ENABLE;
  ALTER TABLE "C##ADAMJDBC"."TEACHING" ADD CONSTRAINT "INSTRUCTOR_FK" FOREIGN KEY ("INSTRUCTOR_ID")
	  REFERENCES "C##ADAMJDBC"."INSTRUCTOR" ("INSTRUCTOR_ID") ENABLE;
